language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
  # install a newer version of CMake:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - pip install .
before_script:
  - /bin/bash .travis_init.sh
# command to run tests
script: python setup.py test 
